USE QLNV 
GO

CREATE table NHANVIEN (
MANV CHAR(5) NOT NULL,
HOTEN NVARCHAR(40) NOT NULL,
GIOITINH NCHAR(3) NOT NULL,
NGAYSINH DATE NOT NULL,
LUONG INT NOT NULL,
MAPHONG CHAR(3) NOT NULL,
SDT CHAR(10),
NGAYBC DATE NOT NULL
PRIMARY KEY(MANV)
)
GO


