use QLNV
go

insert into TDNN (MANV, MANN, TDO) VALUES ('HC001','01', 'A')
insert into TDNN (MANV, MANN, TDO) VALUES ('HC001','02', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('HC002','01', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('HC002','03', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('HC003','01', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD001','01', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD001','02', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD002','01', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD002','02', 'A')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD003','01', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD003','02', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD004','01', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD004','04', 'A')

insert into TDNN (MANV, MANN, TDO) VALUES ('KD004','05', 'A')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD005','01', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD005','02', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD005','03', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KD005','04', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT001','01', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT001','04', 'E')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT002','01', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT002','02', 'B')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT003','01', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT003','03', 'C')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT004','01', 'D')
insert into TDNN (MANV, MANN, TDO) VALUES ('KT005','01', 'C')
go
